services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: flask_api:1.0
    container_name: flask_api
    environment:
      - ENV_VAR=${ENV_VAR}
      - API_TOKEN=${API_TOKEN}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${API_PORT}:3000
    volumes:
      - ./src:/app

  flask_db:
    image: mongo:5.0.8
    container_name: flask_db
    ports:
      - ${MONGODB_PORT}:27017
    volumes:
      - flask_db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  flask_swagger:
    image: swaggerapi/swagger-ui:v4.14.0
    container_name: flask_swagger
    ports:
      - ${SWAGGER_PORT}:8080
    volumes:
      - ./swagger.yaml:/srv/swagger.yaml
    environment:
      SWAGGER_JSON: /srv/swagger.yaml

volumes:
  flask_bdd:
